### ISSUE TITLE
gobject not found

### ISSUE THREAD

**Issue by geboro** [byuphamerator/phamerator-dev#24]
Hello,
Just installed phamerator but its crashing with this error. I do have python-gobject installed. 
Working on Ubuntu 16.04. 
Thanks!

`phamerator-dev $ ./phamerator/Phamerator
Traceback (most recent call last):
  File "./phamerator/Phamerator", line 32, in <module>
    from phamerator import logger, cartographer, PhamDisplay, pham, phamerator_manage_db, config, db_status
  File "./phamerator/../phamerator/cartographer.py", line 6, in <module>
    import gobject
ImportError: No module named gobject
`

**Comment by Truongphi20** [comment]
I also faced the same problem as you for phamerator. Have you solved it yet? Can you show me, please
